#DON'T CHANGE
Version: 2.4

#The world you want to add the Cosmetic item in
WorldName: world

# Choose the name of the cosmetic item name and the title of the main form
Name: "CosmeticMenu"
# The description of the Main Form
Form-Content: "Select a Cosemtic"

Command: true

#Settings for the cosmetic item
Cosmetic:
  # Choose if you want the Cosmetic Item to be enabled or not
  Enable: true

  # Choose the name of the cosmetic item description 
  Des: "Click Me"

  # Choose what item the Cosmetic should be (Default is a nether star (399))
  Item: 399

  # Choose what slot of the player's hotbar or inventory the cosmetic item should appear in (0-8 are the player's hotbar)
  Slot: 4

  # Choose whether to prevent players from dropping or moving the cosmetic item
  Force-Slot: true


Cooldown:
  TnT-Launcher: 60
  Lightning Stick: 60
  Leaper: 60
